# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/adam/repos/sig-gen-name-tbd/vivado/PL_PROJ_MASTER/PL_PROJ/PL_PROJ.cache/wt [current_project]
set_property parent.project_path /home/adam/repos/sig-gen-name-tbd/vivado/PL_PROJ_MASTER/PL_PROJ/PL_PROJ.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-20:part0:1.0 [current_project]
set_property ip_output_repo /home/adam/repos/sig-gen-name-tbd/vivado/PL_PROJ_MASTER/PL_PROJ/PL_PROJ.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/adam/repos/sig-gen-name-tbd/vivado/PL_PROJ_MASTER/PL_PROJ/PL_PROJ.srcs/sources_1/imports/ip/ch_unit_v993/src/ch_unit.v
  /home/adam/repos/sig-gen-name-tbd/vivado/PL_PROJ_MASTER/PL_PROJ/PL_PROJ.srcs/sources_1/imports/ip/clk_enable_signa_ip/src/clk_en_signal.v
  /home/adam/repos/sig-gen-name-tbd/vivado/PL_PROJ_MASTER/PL_PROJ/PL_PROJ.srcs/sources_1/new/four_ch.v
  /home/adam/repos/sig-gen-name-tbd/vivado/PL_PROJ_MASTER/PL_PROJ/PL_PROJ.srcs/sources_1/new/four_gpio_ch.v
  /home/adam/repos/sig-gen-name-tbd/vivado/PL_PROJ_MASTER/PL_PROJ/PL_PROJ.srcs/sources_1/new/gpio_to_ch.v
  /home/adam/repos/sig-gen-name-tbd/vivado/PL_PROJ_MASTER/PL_PROJ/PL_PROJ.srcs/sources_1/imports/ip/clk_enable_signa_ip/src/pos_oneshot.v
  /home/adam/repos/sig-gen-name-tbd/vivado/PL_PROJ_MASTER/PL_PROJ/PL_PROJ.srcs/sources_1/imports/ip/ch_unit_v993/src/ram.v
  /home/adam/repos/sig-gen-name-tbd/vivado/PL_PROJ_MASTER/PL_PROJ/PL_PROJ.srcs/sources_1/imports/ip/ch_unit_v993/src/ram_ctrl.v
  /home/adam/repos/sig-gen-name-tbd/vivado/PL_PROJ_MASTER/PL_PROJ/PL_PROJ.srcs/sources_1/new/pl_sys_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top pl_sys_top -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef pl_sys_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file pl_sys_top_utilization_synth.rpt -pb pl_sys_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
