webtalk_init -webtalk_dir /home/adam/repos/sig-gen-name-tbd/vivado/PL_PROJ_MASTER/PL_PROJ/PL_PROJ.sim/sim_1/behav/xsim/xsim.dir/pl_sys_top_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Apr 14 12:19:38 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f99e6edecc515cb29987d3a8cfa4675d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2bc484ad14e3412da0038ce37385f64a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "27" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "unknown" -context "user_environment"
webtalk_add_data -client project -key os_release -value "unknown" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3762.545 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "300 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "114884_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2383791315 -regid "" -xml /home/adam/repos/sig-gen-name-tbd/vivado/PL_PROJ_MASTER/PL_PROJ/PL_PROJ.sim/sim_1/behav/xsim/xsim.dir/pl_sys_top_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/adam/repos/sig-gen-name-tbd/vivado/PL_PROJ_MASTER/PL_PROJ/PL_PROJ.sim/sim_1/behav/xsim/xsim.dir/pl_sys_top_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/adam/repos/sig-gen-name-tbd/vivado/PL_PROJ_MASTER/PL_PROJ/PL_PROJ.sim/sim_1/behav/xsim/xsim.dir/pl_sys_top_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
